#!/bin/bash
# Script que detecta erros de estilo
# antes de serem submetidos em definitivo ao repositório.

cd $(dirname $(readlink -f $0))
# Este comando navega para o diretório deste arquivo,
# mesmo que o executável referencie este diretório via link simbólico.

error=0
source pre-commit.utilities.sh
source pre-commit.hyphens.sh
exit $error
