#!/bin/bash
# Script que detecta erros de estilo
# antes de serem submetidos em definitivo ao repositório.

error=0
source githooks/pre-commit.utilities.sh
source githooks/pre-commit.hyphens.sh
exit $error
