#!/bin/bash
# Script que detecta erros de estilo
# antes de serem submetidos em definitivo ao repositório.

cd $(dirname $(readlink -f $0))
# Este comando navega para o diretório deste arquivo,
# mesmo que o executável referencie este diretório via link simbólico.

unset GIT_DIR
# Mágicas do Git. GIT_DIR é uma variável de ambiente
# que informa onde está o diretório .git, relativo ao diretório de trabalho.
# Esta variável permite que coloquemos o .git num disco à parte, por exemplo;
# mas, sempre que rodarmos algum comando Git,
# precisaremos informar o valor de GIT_DIR.
# Entretanto, trocar de diretório não altera GIT_DIR, apenas PWD.
# Então, ao rodar algum comando, como 'git diff',
# o Git tentará acessar o diretório $PWD/$GIT_DIR.
# Isso é útil caso mudemos GIT_DIR, pois esta mudança é propagada pelo script;
# mas não podemos mais usar 'cd' adequadamente.
#
# A solução é simplesmente eliminar a variável GIT_DIR da jogada.
# Todos os comandos Git procuram o diretório .git
# nos diretórios pais do diretório atual, caso GIT_DIR não exista.
# Portanto, os comandos como 'git diff' funcionarão
# assim como eles funcionam na linha de comando.

error=0
source pre-commit.utilities.sh
source pre-commit.whitespace.sh
source pre-commit.citeties.sh
source pre-commit.refties.sh
source pre-commit.verbo-ir.sh
source pre-commit.aspell.sh
source pre-commit.forbidden.sh
exit $error
